# start command
# docker-compose -f redis-compose.yml up -d
services:
  redis:
    image: redis:alpine
    container_name: myredis
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data
    command: redis-server --requirepass mypassword --appendonly yes
